const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  //admin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAIL: "FETCH_GENDER_FAIL",

  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAIL: "FETCH_POSITION_FAIL",

  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAIL: "FETCH_ROLE_FAIL",

  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAIL: "EDIT_USER_FAIL",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",

  FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
  FETCH_ALL_USERS_FAIL: "FETCH_ALL_USERS_FAIL",

  FETCH_TOP_BARBER_SUCCESS: "FETCH_TOP_BARBER_SUCCESS",
  FETCH_TOP_BARBER_FAIL: "FETCH_TOP_BARBER_FAIL",

  FETCH_ALL_BARBER_SUCCESS: "FETCH_ALL_BARBER_SUCCESS",
  FETCH_ALL_BARBER_FAIL: "FETCH_ALL_BARBER_FAIL",

  SAVE_DETAIL_BARBER_SUCCESS: "SAVE_DETAIL_BARBER_SUCCESS",
  SAVE_DETAIL_BARBER_FAIL: "SAVE_DETAIL_BARBER_FAIL",

  FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: "FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS",
  FETCH_ALLCODE_SCHEDULE_TIME_FAIL: "FETCH_ALLCODE_SCHEDULE_TIME_FAIL",

  FETCH_REQUIRED_BARBER_INFOR_START: "FETCH_REQUIRED_BARBER_INFOR_START",
  FETCH_REQUIRED_BARBER_INFOR_SUCCESS: "FETCH_REQUIRED_BARBER_INFOR_SUCCESS",
  FETCH_REQUIRED_BARBER_INFOR_FAIL: "FETCH_REQUIRED_BARBER_INFOR_FAIL",
});

export default actionTypes;
